#ifndef __STATE_H__
#define __STATE_H__

enum ST {
    ST_UNDEFINED,
    ST_SUCCESS,
    ST_SOCKET_ERROR,
    ST_EPOLL_ERROR,
    ST_CONNECTION_ERROR,
    ST_ACCEPTOR_ERROR,
    ST_UNIMPLEMENTED
};

#endif //__STATE_H__
